# Generated by Django 5.1.4 on 2025-03-24 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_expire',
            new_name='reset_password_expire',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='rest_password_token',
            new_name='reset_password_token',
        ),
    ]
